#include "syscall_info.h"

struct SyscallDescription syscall_table[] = {
    {"read", {{"fd", ARG_INT}, 
              {"buf", ARG_DATA}, 
              {"count", ARG_INT}}},
    {"write", {{"fd", ARG_INT},
               {"buf", ARG_DATA},
               {"count", ARG_INT}}},
    {"open", {{"pathname", ARG_STRING},
              {"flags", ARG_INT},
              {"mode", ARG_INT}}},
    {"close", {{"fd", ARG_INT}}},
    {"stat", {{"pathname", ARG_STRING},
              {"statbuf", ARG_STAT}}},
    {"fstat", {{"fd", ARG_INT},
               {"statbuf", ARG_STAT}}},
    {"lstat", {{"pathname", ARG_STRING},
               {"statbuf", ARG_STAT}}},
    {"poll", {{"fds", ARG_POLL_FD},
              {"nfds", ARG_INT},
              {"timeout", ARG_INT}}},
    {"lseek", {{"fd", ARG_INT},
               {"offset", ARG_INT},
               {"whence", ARG_INT}}},
    {"mmap", {{"addr", ARG_PTR},
              {"length", ARG_INT},
              {"prot", ARG_INT},
              {"flags", ARG_INT},
              {"fd", ARG_INT},
              {"offset", ARG_INT}}},
};